### ISSUE TITLE
Pull background image from Steam automatically.

### ISSUE THREAD

**Issue by EyreFree** [enums/Calatrava#2]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [README.md](https://github.com/enums/Calatrava/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/enums/Calatrava/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

Big guy, ask for demand, hope template can support Steam ID and then give a switch control whether to automatically pull the background map from Steam.

#### Reproduce

For example, this is [my Steam personal information page](steamcommunity.com/id/EyreFree/), can you add a switch to control this graph automatically as a background map of the whole blog?

#### Other Comment

Nothing more.

**Comment by enums** [comment]
There is a plugin called PCHTTPFilterPlugin in Pjango-Core. You can write a plugin by inheriting it to implement the feature.

**Comment by EyreFree** [comment]
![Fork you!](https://user-images.githubusercontent.com/10757132/34345324-07f41eb6-ea29-11e7-8681-0969237a018e.png)

**Comment by enums** [comment]
Here you are!! https://github.com/enums/Pjango-SteamPlugin
